### ISSUE TITLE
Please add postgresql support.

### ISSUE THREAD

**Issue by invasionofsmallcubes** [t-tiger/gorm-bulk-insert#1]
I would be really great to have postgresql support.

I can help you if you guide me.

**Comment by t-tiger** [comment]
Thanks for request. 

Actually, I've never used PostgresQL. However, as I looked it up, SQL for Bulk Insert is almost the same as MySQL. So I would like to implement it. Please give me some more time...

**Comment by vladislavp** [comment]
1+ for postgres

**Comment by frederikhors** [comment]
@t-tiger, +1 also for me. Would be amazing! Please.

**Comment by t-tiger** [comment]
Sorry for the really late response. 🙏
I'm planning to responsd this week, so please wait a little more.

**Comment by dp0h** [comment]
+1 for postgres

**Comment by pieterclaerhout** [comment]
+1

**Comment by t-tiger** [comment]
Thanks to @pieterclaerhout 's contribution, PostgreSQL support is complete. I'm sorry to have kept waiting for a long time.
