### ISSUE TITLE
Use more prepared statements

### ISSUE THREAD

**Issue by mcandre** [t-tiger/gorm-bulk-insert#10]
Prepared statements are preferable to `sprintf()`-style manipulation, in order to reduce the risk of SQL injection attacks.

**Comment by bombsimon** [comment]
This package doesn't use `Sprintf()` for the values, it's for the placeholders (`?`) used in the prepared statements. This is because the placeholders are of arbitrary length and cannot be hardcoded. Or do you see something I'm missing?

**Comment by bombsimon** [comment]
I'm closing this since the reporter hasn't responded and since `Sprintf()` is only used to add the placeholders which in turn is used as prepared statements. There should be no increased risk for SQL injections in the current code.
