### ISSUE TITLE
Feature: Bulk delete

### ISSUE THREAD

**Issue by mcandre** [t-tiger/gorm-bulk-insert#12]
Please extend bulk operations to DELETE's, in order to help Go applications scale with larger traffic flows.

**Comment by t-tiger** [comment]
Thank you for posting Feature. Originally, this library is for optimization of insert processing, and delete processing is not targeted. If you want to delete multiple records at once, you can achieve this by using where condition via gorm.

For the above reasons, sorry,  I'll close this issue.
