### ISSUE TITLE
Support for automatically adding now-time to CreatedAt and UpdatedAt fields

### ISSUE THREAD

**Issue by faoztas** [t-tiger/gorm-bulk-insert#16]
Hi @t-tiger 

When is automatic now-time support added? 
Is there such a development now?

**Comment by bombsimon** [comment]
What is it that's not working for you? If the fields are named `CreatedAt` or `UpdatedAt`, the value will be set to `time.Now()` on insert, [see here](https://github.com/t-tiger/gorm-bulk-insert/blob/master/bulk_insert.go#L107-L108).

**Comment by t-tiger** [comment]
As @bombsimon wrote, fields of `CreatedAt` and` UpdatedAt` are automatically set to the current time. If there are other time fields, set the time manually.
