### ISSUE TITLE
Return the newly created rows

### ISSUE THREAD

**Issue by tspeterkim** [t-tiger/gorm-bulk-insert#24]
Hi,

After bulk creating new rows in the table, I want to obtain the newly generated rows' ids similar in concept to `mysqli_insert_id` but obviously applied for the entire batch I just inserted. Is there any plan to support this?

Best,
Peter

**Comment by bombsimon** [comment]
As far as I know there's no easy way to tell MySQL or PostgreSQL to return multiple last inserted IDs and I don't know how that would even work to map to the correct record.

The first thing that comes to mind for me is to actually query the database after the insert but I see several issues with this.

* If your constraints allow several identical rows, how do you know which ID is which row?
* If you have set insert options to ignore duplicates, how do you know which row wasn't created?

Do you have any suggestions in mind for how this could be implemented in a reasonable way? If the implementation would be to just query the database again for all records I think it's better to leave it up to the user. Maybe something like this could do?

```go
var (
    myRecords   = []MyType{...}
    toInsert    = make([]interface{}, len(myRecords))
    insertStart = time.Now()
    inserted    []MyType
)

// Convert your slice of your type to an interface slice.
for i := range myRecords {
    toInsert[i] = myRecords[i]
}

// Insert all records, let Gorm handle potential ignores etc.
gormbulk.BulkInsert(db, insertRecords, 3000)

// Query the database for all records of MyType created after the start
// of executing this method. All inserted records with their ID will be stored
// in `inserted`
db.Where("created_at > ?", insertStart).Find(&inserted)

```

**Comment by tspeterkim** [comment]
There's definitely no clean and native way to support this and I agree that it should be left to the user to query once more after the insertion like the example above. In my specific use case, I have decided to apply a constraint on the IDs with AUTO_INCREMENT, therefore I can get the batch of just inserted IDs by getting range of numbers from `LAST_INSERTED_ID() - batch_size` to `LAST_INSERTED_ID()`. There's obviously a lot of assumptions that must be met for the correctness of this logic such as one where the all the insertions will succeed. This solution seems to be the best way so far as this [thread](https://stackoverflow.com/questions/7333524/how-can-i-insert-many-rows-into-a-mysql-table-and-return-the-new-ids) indicates. Overall, since there are very specific constraints required to support this functionality, it shouldn't be built in to this library.

**Comment by bombsimon** [comment]
Closing this since it's been quiet for over a month and the author said it should **not** be implemented in this library.
