### ISSUE TITLE
Error 1615: Prepared statement needs to be re-prepared 

### ISSUE THREAD

**Issue by piotrkochan** [t-tiger/gorm-bulk-insert#25]
I  don't know why but I'm getting a lot of errors like:

```
(/home/kochan/go/pkg/mod/github.com/t-tiger/gorm-bulk-insert@v1.3.0/bulk_insert.go:95) 
[2020-02-20 14:09:28]  Error 1615: Prepared statement needs to be re-prepared

**Comment by bombsimon** [comment]
Do you have any code that may reproduce this error message? Are you by any chance inserting to a view rather than a table?

I'll try to see if I can reproduce the issue on my end so please let me know if you figure something out.

**EDIT**: What version of MySQL are you using? Also, what's your `table_definition_cache`? 

```sql
SELECT @@GLOBAL.table_definition_cache;
```

**Comment by bombsimon** [comment]
Just creating a view does not reproduce the issue. Example code to test creating a table, a view for the table and inserting to the view. (Sorry for long example).

<details><summary>Example code</summary>

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	"github.com/jinzhu/gorm"
	gormbulk "github.com/t-tiger/gorm-bulk-insert"

	_ "github.com/jinzhu/gorm/dialects/mysql"
)

const (
	testDSN = "root:root@/test_view?parseTime=1"
)

// MyType is for testing.
type MyType struct {
	Value string
}

// MyTypeView is for testing.
type MyTypeView struct {
	Value string
}

func main() {
	var (
		sqlDB, _ = sql.Open("mysql", testDSN)
		db, _    = gorm.Open("mysql", testDSN)
		logger   = log.New(os.Stdout, "[DB DEBUG] ", log.LstdFlags)
	)

	db.LogMode(true)
	db.SetLogger(logger)

	defer db.Close()

	initCommands := []string{
		fmt.Sprintf("DROP DATABASE IF EXISTS `%s`", "test_view"),
		fmt.Sprintf("CREATE DATABASE `%s`", "test_view"),
	}

	for _, q := range initCommands {
		if _, err := sqlDB.Exec(q); err != nil {
			panic(err)
		}
	}

	// Create base table
	db.AutoMigrate(&MyType{})

	// Create view
	if err := db.
		Exec("CREATE VIEW `my_type_views` AS SELECT * FROM `my_types`").
		Error; err != nil {
		panic(err)
	}

	toInsert := []interface{}{
		MyTypeView{Value: "first"},
		MyTypeView{Value: "second"},
	}

	if err := gormbulk.BulkInsert(db, toInsert, 3000); err != nil {
		panic(err)
	}
}
```
</details>

<details><summary>Output from the code</summary>

```sh
$ go run main.go | gsed "s#$HOME##g"
[DB DEBUG] 2020/02/20 14:53:44 sql/tmp/reprepare/main.go:5321.303367msCREATE TABLE `my_types` (`value` varchar(255) )[] 0
[DB DEBUG] 2020/02/20 14:53:44 sql/tmp/reprepare/main.go:5713.613404msCREATE VIEW `my_type_views` AS SELECT * FROM `my_types`[] 0
[DB DEBUG] 2020/02/20 14:53:44 sql/go/pkg/mod/github.com/t-tiger/gorm-bulk-insert@v1.3.0/bulk_insert.go:9531.290081msINSERT INTO `my_type_views` (`value`) VALUES (?), (?) [first second] 2
```
</details>

**Comment by bombsimon** [comment]
According to [MySQL Bugs: #42041](https://bugs.mysql.com/bug.php?id=42041) this seems to be resolved by bumping the value of `table_definition_cache` (see especially the response from Derek Hemmes).

In MySQL 5.7 this is defaulted to `2000` but I can see people using way higher values than that. I guess it depends on things such as server load. Also it seems more frequent in older versions of MySQL so if possible please try this in a recent version.

**Comment by piotrkochan** [comment]
I've cleaned up database a little bit and the problem seems to be resolved now. Thanks for Your time and awesome library!
