### ISSUE TITLE
[Question] SQL injection potential flaw?

### ISSUE THREAD

**Issue by EnoRage** [t-tiger/gorm-bulk-insert#38]
Just want to ask, does anyone check is BulkInsert protected from SQL injections? I see that there are raw strings that we send to DB. Am I right that it is important to validate all the data to prevent security issues using that package?

**Comment by bombsimon** [comment]
Hi!

The raw strings are to write the placeholders (`?`) which is used to **avoid** injection.  No value is ever written as raw SQL in this library but are passed as values to [`Exec`](https://github.com/jinzhu/gorm/blob/7180bd0f27d167f18c253c32d548c7de3adc6b0d/interface.go#L10). Also included in the raw string is the column names but they're passed via [`Quote`](https://github.com/jinzhu/gorm/blob/master/scope.go#L69-L80). The column names are from your structs so they're not really affected by this, but **if** you named your columns to `username; DROP TABLE users` it would still be at no risk.

I can't swear that `gorm` isn't vulnerable to injections but I think it looks fine. It's more than five years old with nearly 20k stars so someone should've noticed that by now.
