### ISSUE TITLE
bulk insert did not return and fill models primary key

### ISSUE THREAD

**Issue by 524243642** [t-tiger/gorm-bulk-insert#44]
bulk insert did not return and fill models primary key,  primary key is used in some situations

**Comment by bombsimon** [comment]
This has been discussed before and is not really possible. See #24 for a short discussion regarding how this would even be possible.

I'm not sure if and if so how `gorm` tackles this issue in v2.0 but the latest release do have support for bulk insert so you should try to use that release and raise any issues in the [gorm repository](https://github.com/go-gorm/gorm/issues)
