### ISSUE TITLE
Incompatible with new Gorm module name

### ISSUE THREAD

**Issue by muety** [t-tiger/gorm-bulk-insert#46]
I'd like to use this library with the latest version of Gorm, however, I'm getting the following error then.

```
Cannot use 'r.db' (type *"gorm.io/gorm".DB) as type *"github.com/jinzhu/gorm".DB
```

**Comment by muety** [comment]
Never mind, just found that Gorm apparently has [batch insert support](https://gorm.io/docs/create.html#Batch-Insert) itself now.

**Comment by bombsimon** [comment]
Yes, this is correct! This is no longer needed with the latest version of Gorm. Closing this!
