### ISSUE TITLE
bulk insert do not response primary key?

### ISSUE THREAD

**Issue by GoJaden** [t-tiger/gorm-bulk-insert#48]
**When using gorm batches, it seems that you cannot assign values to the primary key of struct**

**Comment by bombsimon** [comment]
You should be able to set the value for a primary key, however if the field used as a primary key is set to `AUTO_INCREMENT` it [will be ignored](https://github.com/t-tiger/gorm-bulk-insert/blob/96fee43e98db29c20eb38101977b2276e3852a2c/bulk_insert.go#L122).

If you field is not set to `AUTO_INCREMENT`, do you have a reproducible example (including schema creation) to provide?

Also, I suggest that you look into switching to [gorm.io/gorm](https://gorm.io/). It's the v2 of original [jinzhu/gorm](https://github.com/jinzhu/gorm) which this project targets. V2 supports bulk inserting natively.
