### ISSUE TITLE
Incompatible version of go-sqlite3 version - 2.0.3 

### ISSUE THREAD

**Issue by Shriram-RP** [t-tiger/gorm-bulk-insert#51]
Hi gorm-bulk-insert team,

We at the platform team of razorpay internally use bulk-insert which internally uses github.com/jinzhu/gorm v1.9.12 and creates an indirect dependency on github.com/mattn/go-sqlite3 v2.0.3.

Reference :- https://github.com/t-tiger/gorm-bulk-insert/blob/master/go.mod#L14

Now, this setup was working fine for us till last week and suddenly we had a failure in our docker build for github actions citing
github.com/mattn/go-sqlite3@v2.0.3+incompatible: unknown revision v2.0.3

Can you resolve this instable version and help us to continue using bulk insert?

Thanks,
Shriram

**Comment by bombsimon** [comment]
@Shriram-RP This should now be fixed and released in v2.1.0. Could you try upgrading `gorm-bulk-insert` to the latest version and see if this resolves your issue? If not let's re-open this issue!
