### ISSUE TITLE
Support gorm's insert_option for bulk upsert

### ISSUE THREAD

**Issue by rohansuri** [t-tiger/gorm-bulk-insert#6]
Hi @t-tiger,
Would you accept a PR that adds support for looking up [gorm:insert_option](https://github.com/jinzhu/gorm/blob/master/callback_create.go#L89) and adding it to the prepared bulk insert query?

This lets users pass in custom options, like [ON DUPLICATE KEY UPDATE x=VALUES(x)](https://github.com/jinzhu/gorm/issues/1307#issuecomment-502733676), allowing bulk upsert.

**Comment by bombsimon** [comment]
Closing this since this was solved in #23.
