### ISSUE TITLE
Field ignored if name is "id" and is a PK regardless of auto_increment

### ISSUE THREAD

**Issue by iBeb** [t-tiger/gorm-bulk-insert#7]
I'm facing an issue with the bulk insert for this struct:

```
type GeoObject struct {
	ID               uint32  `json:"-" gorm:"column:id;primary_key;auto_increment:false"`
	CountryCode      string  `json:"countryCode" gorm:"type:varchar(2);column:country_code"`
	PostalCode       string  `json:"postalCode" gorm:"type:varchar(10);column:postal_code"`
	Latitude         float32 `json:"latitude" gorm:"column:latitude"`
	Longitude        float32 `json:"longitude" gorm:"column:longitude"`
...
}
```
The field ID is defined as the primary key but with an explicit `auto_increment:false` as the app sets it by itself based on another counter.

Even with valid entries like
`{ID:7 CountryCode:cn PostalCode:510000 Latitude:23.12472 Longitude:113.23861...` the insert fails with MySQL returning the error: `Insert failed Error 1364: Field 'id' doesn't have a default value`.

Looking at the code, I see that fields with the name `id` and set as a PK are ignored by `extractMapValue`, regardless if the column has an `auto_increment` or not.
It is nonetheless a valid definition to have a table with a column `id` set as a PK with no `auto_increment`.

**Comment by t-tiger** [comment]
@iBeb

Thank you for the report. The following commits addressed the problem.

https://github.com/t-tiger/gorm-bulk-insert/commit/7b3d108c15e2e107b8790a5ebceafbf74f8a7685

As a result, primary_key which is not auto_increment will use the set value.
